import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit 
from sklearn.metrics import r2_score

Spatial_size = 16
Temporal_size = 8

# Load the data generated by the moving block bootstrap script
# Update this filename if your previous script saved it to a specific folder (e.g., './Analyzed_Data/...')
filename = 'Analyzed_Data/Spatial_size_' + str(Spatial_size) + '_Temporal_size_' +str(Temporal_size) + '_analysis.csv'
df = pd.read_csv(filename)

beta_array = df['Beta'].to_numpy()
avg_plaq = df['Avg Plaq'].to_numpy()
plaq_sus = df['Plaq Sus'].to_numpy()
SD_avg_plaq = df['Bootstrap Plaq SD'].to_numpy()
SD_plaq_sus = df['Bootstrap Sus SD'].to_numpy()

plt.rc('font', size=15)

# --- Plot 1: Average Plaquette ---
plt.figure(figsize=(8, 6))
plt.errorbar(beta_array, avg_plaq, yerr=SD_avg_plaq, fmt='o', label='Monte Carlo Data', color='blue', ecolor='red', elinewidth=3)
plt.title('Average Plaquette vs Beta')
plt.xlabel('Beta')
plt.ylabel('Average Plaquette')
plt.legend()
plt.show()

# --- Plot 2: Plaquette Susceptibility ---
plt.figure(figsize=(8, 6))
plt.errorbar(beta_array, plaq_sus, yerr=SD_plaq_sus, fmt='o', label='Monte Carlo Data', color='blue', ecolor='red', elinewidth=3)
plt.title('Plaquette Susceptibility vs Beta (Raw)')
plt.xlabel('Beta')
plt.ylabel('Plaquette Susceptibility')
plt.legend()
plt.show()

#--------------------------------------------------------
# Lorentzian Fitting on Raw Susceptibility Data
# ---------------------------------------------------------

# Automatically find the peak in the data to center our fit
max_idx = np.argmax(plaq_sus)
estimated_critical_beta = beta_array[max_idx]
estimated_peak_height = plaq_sus[max_idx]

# Define a window around the peak to use for the fit. 
# You can widen or narrow this (0.005) depending on how broad your peak is.
beta_window = 0.005 
beta_min = estimated_critical_beta - beta_window
beta_max = estimated_critical_beta + beta_window

# Guess [x0, gamma, a]
initial_guess = [estimated_critical_beta, 0.002, estimated_peak_height]

print(f"Auto-detected peak near Beta = {estimated_critical_beta}. Fitting between {beta_min:.4f} and {beta_max:.4f}...")

# Mask the data to only fit around the peak
mask = (beta_array >= beta_min) & (beta_array <= beta_max)

beta_fit = beta_array[mask]
sus_fit = plaq_sus[mask]
sus_err_fit = SD_plaq_sus[mask]

# Safety check to prevent the curve_fit error if the window is too small
if len(beta_fit) < 3:
    raise ValueError(f"Not enough data points found between {beta_min:.4f} and {beta_max:.4f}. Increase 'beta_window'.")

def lorentzian(x, x0, gamma, a):
    return a * gamma**2 / ((x - x0)**2 + gamma**2) 

# Fit the curve, passing the bootstrap errors as sigma to weight the fit
param, pcov = curve_fit(
    lorentzian, 
    beta_fit, 
    sus_fit, 
    p0=initial_guess, 
    sigma=sus_err_fit,      # Weight the fit by the bootstrap errors
    absolute_sigma=True     # Treat sigma as absolute errors to get correct pcov
)

fitA, fitB, fitC = param

# The standard deviation of the parameters is the square root of the diagonal of the covariance matrix
perr = np.sqrt(np.diag(pcov))
SD_critical_beta = perr[0]
SD_FWHM = 2 * perr[1]  # FWHM is 2*gamma, so error is 2 * error of gamma
SD_peak_height = perr[2]

x0 = fitA
gamma = fitB
a = fitC

R2 = r2_score(sus_fit, lorentzian(beta_fit, fitA, fitB, fitC))
R2 = round(R2, 4)

# Generate a continuous curve for plotting the fit
cts_beta = np.linspace(beta_min, beta_max, 1000)
fitY = lorentzian(cts_beta, fitA, fitB, fitC)

# --- Plot 3: Lorentzian Fit Overlaid ---
plt.figure(figsize=(8, 6))
plt.errorbar(beta_fit, sus_fit, yerr=sus_err_fit, fmt='o', label='Data (Peak Region)', color='blue', ecolor='red', elinewidth=3)
plt.plot(cts_beta, fitY, '-', label='Lorentzian Fit R^2='+str(R2), color='black', alpha=0.7)
plt.legend()
plt.title('Plaquette Susceptibility vs Beta (Fitted)')
plt.xlabel('Beta')
plt.ylabel('Plaquette Susceptibility')  
plt.show()

# Print out the calculated statistics
print('Critical Beta:', x0, '+/-', SD_critical_beta)
print('FWHM:', 2*gamma, '+/-', SD_FWHM)
print('Peak Height:', a, '+/-', SD_peak_height)
print(f"{Spatial_size}^3*{Temporal_size} , {x0} , {2*gamma} , {a} , {SD_critical_beta} , {SD_FWHM} , {SD_peak_height}")